### ISSUE TITLE
[error] [slackbot-reply:731077db.585268] TypeError: Cannot set property 'channel' of undefined

### ISSUE THREAD

**Issue by chaitanya9249** [slickplaid/node-slack-mailgun#3]
Hi
This is chaitanya,
I am using **npm i slack** in node-red for slack messenger.I want to get a file while I issue a command in slack messenger.But while I issue a command in slack messenger I got an issue as like 

 **[error] [slackbot-reply:731077db.585268] TypeError: Cannot set property 'channel' of undefined**

Here is my code:

**PrepareRequest Function**
=======================
msg.payload = {
//      user: msg.message.user, 
//      text: msg.message.text,
//      teamId: "T33BD84EP",
//      channelId: "C33DJFJLA"
        source: "Slack", 
        type: 'message',
        channel: '#development',//'C33DJFJLA',
        user: msg.message.user,
        text: msg.message.text,
        team: 'T33BD84EP'
};

return msg;

**Prepare Response**
==================
      var json = msg.payload.reply;
      if (json.attachment) {
          var attachment_array = JSON.stringify(json.attachment)
          var slack = global.get("slack");
          msg.payload = slack.api.test(JSON.stringify(msg.payload.reply), console.log)
      }
return msg;

**Node-Red Flow**
================
![image](https://cloud.githubusercontent.com/assets/25222593/23695282/5aa13902-0404-11e7-82fa-a01997cb74f2.png)

If you people have any idea about that please let me know..

**Comment by slickplaid** [comment]
Hi Chaitanya,

It's been a long while since I wrote this and/or updated it and quite possibly a parent package updated with breaking changes in it. 

The best I can do is try and take a look here in the next few weeks. If you find out anything more about it, feel free to submit a pull request or give more details. Any more info about the issue would be helpful.

Thanks!
